"""initial schema

Revision ID: 7c91af7c4fa2
Revises: 
Create Date: 2026-08-31 16:52:49.643046

"""
from alembic import op
import sqlalchemy as sa


revision = '7c91af7c4fa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('items',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_items_tenant_name')
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_tenant_id'), 'items', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'firm_admin', 'staff', 'viewer', name='user_role'), nullable=False),
    sa.Column('theme_preference', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('advance_salaries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjusted_status', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advance_salaries_entry_date'), 'advance_salaries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_advance_salaries_tenant_id'), 'advance_salaries', ['tenant_id'], unique=False)
    op.create_table('cashbook_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('credit', 'debit', 'sales_payment', 'purchase_payment', 'salary', 'advance_salary', 'transfer', name='cashbook_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('cash', 'bank', 'upi', name='payment_mode'), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('linked_ref_type', sa.String(), nullable=True),
    sa.Column('linked_ref_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashbook_entries_entry_date'), 'cashbook_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_cashbook_entries_tenant_id'), 'cashbook_entries', ['tenant_id'], unique=False)
    op.create_table('purchase_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('item_desc', sa.String(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_entries_entry_date'), 'purchase_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_purchase_entries_tenant_id'), 'purchase_entries', ['tenant_id'], unique=False)
    op.create_table('salary_payments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('cash', 'bank', 'upi', name='paymentmode'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_payments_entry_date'), 'salary_payments', ['entry_date'], unique=False)
    op.create_index(op.f('ix_salary_payments_tenant_id'), 'salary_payments', ['tenant_id'], unique=False)
    op.create_table('sales_entries',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('item_desc', sa.String(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_entries_entry_date'), 'sales_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_sales_entries_tenant_id'), 'sales_entries', ['tenant_id'], unique=False)
    op.create_table('purchase_payments',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_entry_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('cash', 'bank', 'upi', name='paymentmode'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_entry_id'], ['purchase_entries.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_payments_entry_date'), 'purchase_payments', ['entry_date'], unique=False)
    op.create_index(op.f('ix_purchase_payments_tenant_id'), 'purchase_payments', ['tenant_id'], unique=False)
    op.create_table('sales_payments',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('sales_entry_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('cash', 'bank', 'upi', name='paymentmode'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_entry_id'], ['sales_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_payments_entry_date'), 'sales_payments', ['entry_date'], unique=False)
    op.create_index(op.f('ix_sales_payments_tenant_id'), 'sales_payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_payments_tenant_id'), table_name='sales_payments')
    op.drop_index(op.f('ix_sales_payments_entry_date'), table_name='sales_payments')
    op.drop_table('sales_payments')
    op.drop_index(op.f('ix_purchase_payments_tenant_id'), table_name='purchase_payments')
    op.drop_index(op.f('ix_purchase_payments_entry_date'), table_name='purchase_payments')
    op.drop_table('purchase_payments')
    op.drop_index(op.f('ix_sales_entries_tenant_id'), table_name='sales_entries')
    op.drop_index(op.f('ix_sales_entries_entry_date'), table_name='sales_entries')
    op.drop_table('sales_entries')
    op.drop_index(op.f('ix_salary_payments_tenant_id'), table_name='salary_payments')
    op.drop_index(op.f('ix_salary_payments_entry_date'), table_name='salary_payments')
    op.drop_table('salary_payments')
    op.drop_index(op.f('ix_purchase_entries_tenant_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_entry_date'), table_name='purchase_entries')
    op.drop_table('purchase_entries')
    op.drop_index(op.f('ix_cashbook_entries_tenant_id'), table_name='cashbook_entries')
    op.drop_index(op.f('ix_cashbook_entries_entry_date'), table_name='cashbook_entries')
    op.drop_table('cashbook_entries')
    op.drop_index(op.f('ix_advance_salaries_tenant_id'), table_name='advance_salaries')
    op.drop_index(op.f('ix_advance_salaries_entry_date'), table_name='advance_salaries')
    op.drop_table('advance_salaries')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_items_tenant_id'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
